name: Keep Server Alive
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

    steps:
      - name: Check secrets
        id: check-secrets
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "::warning::Secrets missing. API wake-up skipped."
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          fi

      - name: Wake up Render (API)
        if: ${{ steps.check-secrets.outputs.has_secrets == 'true' }}
        run: |
          echo "Starting API wake-up..."
          curl -v -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/restart" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json"

      - name: Healthcheck
        run: |
          echo "Performing healthcheck..."
          curl \
            --max-time 120 \
            --retry 3 \
            --retry-delay 30 \
            --fail \
            -X GET "https://report-processor-fullstack.onrender.com/health"
          echo "✅ Healthcheck successful"

      - name: Log timestamp
        run: |
          echo "Last executed: $(date -u +'%Y-%m-%dT%H:%M:%S') UTC"