name: Keep Server Alive
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Wake up Render (API)
        if: ${{ secrets.RENDER_API_KEY != '' && secrets.RENDER_SERVICE_ID != '' }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/restart" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"


      - name: Send healthcheck request
        run: |
          curl \
            --max-time 120 \
            --retry 3 \
            --retry-delay 30 \
            -X GET "https://report-processor-fullstack.onrender.com/health"
          echo "✅ Healthcheck completed"

      - name: Log timestamp
        run: date -u +"%Y-%m-%d %H:%M:%S UTC"